### ISSUE TITLE
Receiving a non-JSON message will crash the server

### ISSUE THREAD

**Issue by gdongca** [p-fedyukovich/nestjs-google-pubsub-microservice#43]
Hi. If I send a pure string message to the topic, the first line of GCPubSubServer.handleMessage will try to parse JSON and will crash the service (not recoverable unless restart the service). Ideally I think the handleMessage should be able to handle non-JSON message and let the app deal with it. Or if it does requires JSON format, it should just log an error and return instead of crashing the service. Thanks!

https://github.com/p-fedyukovich/nestjs-google-pubsub-microservice/blob/master/lib/gc-pubsub.server.ts#L148

Waiting for the debugger to disconnect...
undefined:1
what's up?
^

SyntaxError: Unexpected token 'w', "what's up?" is not valid JSON
    at JSON.parse (<anonymous>)
    at GCPubSubServer.handleMessage (/Users/guangyudong/Codes/autogpt-v2-monorepo-2/node_modules/.pnpm/nestjs-google-pubsub-microservice@10.1.0_@google-cloud+pubsub@4.5.0_@nestjs+common@10.3.10_@n_bsqrieua4brdvvyhk4k62f3uly/node_modules/nestjs-google-pubsub-microservice/lib/gc-pubsub.server.ts:148:29)
    at Subscription.<anonymous> (/Users/guangyudong/Codes/autogpt-v2-monorepo-2/node_modules/.pnpm/nestjs-google-pubsub-microservice@10.1.0_@google-cloud+pubsub@4.5.0_@nestjs+common@10.3.10_@n_bsqrieua4brdvvyhk4k62f3uly/node_modules/nestjs-google-pubsub-microservice/lib/gc-pubsub.server.ts:122:20)
    at Subscription.emit (node:events:519:28)
    at Subscriber.<anonymous> (/Users/guangyudong/Codes/autogpt-v2-monorepo-2/node_modules/.pnpm/@google-cloud+pubsub@4.5.0/node_modules/@google-cloud/pubsub/src/subscription.ts:329:38)
    at Subscriber.emit (node:events:519:28)
    at <anonymous> (/Users/guangyudong/Codes/autogpt-v2-monorepo-2/node_modules/.pnpm/@google-cloud+pubsub@4.5.0/node_modules/@google-cloud/pubsub/src/lease-manager.ts:243:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by p-fedyukovich** [comment]
Fixed by #53
